### ISSUE TITLE
'Bot' sends messages as markdown formatting instead of plain text?

### ISSUE THREAD

**Issue by b1bradders** [zaida04/g.js-self#4]
If you check the message the code sends, it shows it as formatted in markdown and there is a weird space at the bottom of any text send by the 'Bot'
<img width="404" alt="Screenshot 2021-04-05 at 15 18 44" src="https://user-images.githubusercontent.com/69256931/113583970-3825fc00-9622-11eb-83c2-f23536102f33.png">

**Comment by b1bradders** [comment]
Here is a YouTube vid of me doing this: https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by zaida04** [comment]
You'd think I'd have that URL memorized by now, but I digress. Do you still have an actual issue or was that just meant as a lead up lol.

**Comment by b1bradders** [comment]
I have an actual issue lol.

**Comment by zaida04** [comment]
As for the issue you have described, I really can't seem to understand what the actual issue is. Which space are you talking about? The space between the "Channel ID" and "regular message" lines? This doesn't really seem like something the *library* has control over and sounds more like a qualm with the API itself.
